# Generated by Django 4.2.5 on 2023-10-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at']},
        ),
    ]
